sudo: false
language: php
php:
  - 5.6
  - 7.2

notifications:
  email: false

install:
  - composer install --dev --no-interaction
script:
  - phpunit --configuration Tests/phpunit.xml
after_script:
  - ./.codeclimate.sh
